In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [44]:
data = dict()

files = ['PCECC96', 'WILL5000INDFC','GDPDEF','TB3MS']

for i in files:
    data[i] = pd.read_csv(i+'.csv')
    data[i]['DATE'] = pd.to_datetime(data[i]['DATE'])
    data[i] = data[i].set_index('DATE')

[data[i][i] for i in files]
dataframe = pd.concat([data[i][i] for i in files], axis=1, join='inner')
dataframe = dataframe.reset_index()
dataframe['qt'] = dataframe['DATE'].dt.quarter
dataframe['year'] = dataframe['DATE'].dt.year

In [45]:
dataframe.columns = ['date', 'rConsumption', 'USGrowth', 'GDPDef', 'RFR', 'qt','year']

In [46]:
for i in ['rConsumption', 'USGrowth', 'GDPDef', 'RFR' ]:
    dataframe[i] = pd.to_numeric(dataframe[i])
dataframe['GDPDef_p'] = dataframe.GDPDef.pct_change()

In [47]:
for i in ['USGrowth', 'RFR']:
    dataframe['r'+i] = dataframe[i]/(1+dataframe['GDPDef_p'])

In [48]:
dataframe

,date,rConsumption,USGrowth,GDPDef,RFR,qt,year,GDPDef_p,rUSGrowth,rRFR
0,1971-01-01,3156.978,1.080000,22.391,3.840000,1,1971,NaN,NaN,NaN
1,1971-04-01,3185.993,1.136667,22.685,4.250000,2,1971,0.013130,1.121935,4.194920
2,1971-07-01,3211.394,1.113333,22.916,5.010000,3,1971,0.010183,1.102111,4.959498
3,1971-10-01,3264.679,1.113333,23.107,4.230000,4,1971,0.008335,1.104131,4.195035
4,1972-01-01,3307.767,1.240000,23.458,3.436667,1,1972,0.015190,1.221446,3.385244
5,1972-04-01,3370.736,1.280000,23.604,3.770000,2,1972,0.006224,1.272083,3.746681
6,1972-07-01,3422.682,1.293333,23.830,4.220000,3,1972,0.009575,1.281068,4.179978
7,1972-10-01,3503.001,1.356667,24.134,4.863333,4,1972,0.012757,1.339578,4.802073
8,1973-01-01,3566.957,1.306667,24.412,5.700000,1,1973,0.011519,1.291787,5.635089
9,1973-04-01,3565.349,1.196667,24.787,6.603333,2,1973,0.015361,1.178562,6.503432
10,1973-07-01,3577.898,1.243333,25.270,8.323333,3,1973,0.019486,1.219569,8.164245
11,1973-10-01,3567.227,1.176667,25.773,7.500000,4,1973,0.019905,1.153702,7.353626
12,1974-01-01,3535.312,1.130000,26.260,7.616667,1,1974,0.018896,1.109044,7.475413
13,1974-04-01,3548.041,1.020000,26.880,8.153333,2,1974,0.023610,0.996473,7.965273
14,1974-07-01,3563.282,0.833333,27.668,8.190000,3,1974,0.029315,0.809600,7.956744
15,1974-10-01,3511.197,0.836667,28.482,7.360000,4,1974,0.029420,0.812755,7.149655
16,1975-01-01,3540.647,0.976667,29.129,5.750000,1,1975,0.022716,0.954973,5.622284
17,1975-04-01,3598.886,1.120000,29.562,5.393333,2,1975,0.014865,1.103595,5.314336
18,1975-07-01,3650.035,1.076667,30.084,6.330000,3,1975,0.017658,1.057985,6.220166
19,1975-10-01,3689.285,1.116667,30.587,5.626667,4,1975,0.016720,1.098303,5.534137
20,1976-01-01,3763.048,1.276667,30.911,4.916667,1,1976,0.010593,1.263285,4.865132
21,1976-04-01,3797.670,1.300000,31.222,5.156667,2,1976,0.010061,1.287051,5.105301
22,1976-07-01,3837.654,1.336667,31.626,5.150000,3,1976,0.012940,1.319592,5.084212
23,1976-10-01,3887.447,1.363333,32.192,4.673333,4,1976,0.017897,1.339363,4.591167
24,1977-01-01,3933.268,1.353333,32.711,4.630000,1,1977,0.016122,1.331861,4.556539
25,1977-04-01,3954.596,1.360000,33.172,4.840000,2,1977,0.014093,1.341100,4.772737
26,1977-07-01,3991.989,1.366667,33.576,5.496667,3,1977,0.012179,1.350222,5.430529
27,1977-10-01,4052.010,1.353333,34.301,6.110000,4,1977,0.021593,1.324729,5.980857
28,1978-01-01,4074.774,1.313333,34.800,6.393333,1,1978,0.014548,1.294501,6.301659
29,1978-04-01,4161.887,1.466667,35.465,6.476667,2,1978,0.019109,1.439165,6.355223
...,...,...,...,...,...,...,...,...,...,...
164,2012-01-01,10973.303,56.248710,99.320,0.066667,1,2012,0.006251,55.899279,0.066253
165,2012-04-01,10989.585,56.280159,99.713,0.086667,2,2012,0.003957,56.058341,0.086325
166,2012-07-01,11007.517,58.517778,100.225,0.103333,3,2012,0.005135,58.218839,0.102805
167,2012-10-01,11056.852,59.662742,100.737,0.086667,4,2012,0.005109,59.359504,0.086226
168,2013-01-01,11114.186,64.625000,101.139,0.086667,1,2013,0.003991,64.368133,0.086322
169,2013-04-01,11122.185,68.969531,101.431,0.050000,2,2013,0.002887,68.770981,0.049856
170,2013-07-01,11167.422,72.637812,101.918,0.033333,3,2013,0.004801,72.290724,0.033174
171,2013-10-01,11263.648,77.266406,102.517,0.063333,4,2013,0.005877,76.814944,0.062963
172,2014-01-01,11308.019,80.955574,102.937,0.046667,1,2014,0.004097,80.625262,0.046476
173,2014-04-01,11431.831,83.512063,103.512,0.033333,2,2014,0.005586,83.048161,0.033148
174,2014-07-01,11554.841,86.996406,103.957,0.026667,3,2014,0.004299,86.624008,0.026553
175,2014-10-01,11694.969,88.326719,104.123,0.023333,4,2014,0.001597,88.185902,0.023296
176,2015-01-01,11792.119,91.507541,104.090,0.026667,1,2015,-0.000317,91.536552,0.026675
177,2015-04-01,11885.980,93.867937,104.675,0.020000,2,2015,0.005620,93.343334,0.019888
178,2015-07-01,11976.589,90.629688,105.048,0.040000,3,2015,0.003563,90.307883,0.039858
179,2015-10-01,12030.223,91.113438,105.049,0.123333,4,2015,0.000010,91.112570,0.123332
180,2016-01-01,12124.214,86.048525,104.941,0.286667,1,2016,-0.001028,86.137081,0.286962
181,2016-04-01,12211.285,92.536094,105.657,0.256667,2,2016,0.006823,91.909009,0.254927
182,2016-07-01,12289.063,97.382344,106.043,0.296667,3,2016,0.003653,97.027869,0.295587
183,2016-10-01,12365.312,99.383810,106.551,0.430000,4,2016,0.004791,98.909980,0.427950
184,2017-01-01,12438.898,106.462258,107.058,0.590000,1,2017,0.004758,105.958079,0.587206
185,2017-04-01,12512.899,109.988095,107.411,0.890000,2,2017,0.003297,109.626626,0.887075
186,2017-07-01,12586.281,113.484127,107.973,1.036667,3,2017,0.005232,112.893442,1.031271
187,2017-10-01,12729.713,120.347619,108.713,1.206667,4,2017,0.006854,119.528423,1.198453
188,2018-01-01,12782.902,126.824098,109.355,1.560000,1,2018,0.005905,126.079541,1.550842
189,2018-04-01,12909.192,126.711094,110.281,1.840000,2,2018,0.008468,125.647135,1.824550
190,2018-07-01,13019.802,134.328571,110.767,2.040000,3,2018,0.004407,133.739193,2.031049
191,2018-10-01,13066.302,126.443492,111.256,2.316667,4,2018,0.004415,125.887739,2.306484
192,2019-01-01,13103.317,128.690492,111.473,2.386667,1,2019,0.001950,128.439975,2.382021
193,2019-04-01,13241.083,136.506508,112.164,2.300000,2,2019,0.006199,135.665543,2.285831

In [42]:
dataframe.to_csv('dataset.csv')