In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [50]:
data = dict()

files = ['PCECC96', 'WILL5000INDFC','GDPDEF','TB3MS']

for i in files:
    data[i] = pd.read_csv(i+'.csv')
    data[i]['DATE'] = pd.to_datetime(data[i]['DATE'])
    data[i] = data[i].set_index('DATE')

[data[i][i] for i in files]
dataframe = pd.concat([data[i][i] for i in files], axis=1, join='inner')
dataframe = dataframe.reset_index()
dataframe['qt'] = dataframe['DATE'].dt.quarter
dataframe['year'] = dataframe['DATE'].dt.year

In [51]:
dataframe.columns = ['date', 'rConsumption', 'USGrowth', 'GDPDef', 'RFR', 'qt','year']

In [52]:
for i in ['rConsumption', 'USGrowth', 'GDPDef', 'RFR' ]:
    dataframe[i] = pd.to_numeric(dataframe[i])
dataframe['GDPDef_p'] = dataframe.GDPDef.pct_change()
dataframe['RFR_Q'] = dataframe.RFR/(4*100) - dataframe.GDPDef_p
dataframe['Rt'] = dataframe.USGrowth.pct_change() - dataframe.GDPDef_p + 1
dataframe['mt'] = .99* (dataframe.rConsumption.pct_change()+1)**(-6)

In [53]:
dataframe

,date,rConsumption,USGrowth,GDPDef,RFR,qt,year,GDPDef_p,RFR_Q,Rt,mt
0,1971-01-01,3156.978,1.080000,22.391,3.840000,1,1971,NaN,NaN,NaN,NaN
1,1971-04-01,3185.993,1.136667,22.685,4.250000,2,1971,0.013130,-0.002505,1.039339,0.937121
2,1971-07-01,3211.394,1.113333,22.916,5.010000,3,1971,0.010183,0.002342,0.969289,0.943936
3,1971-10-01,3264.679,1.113333,23.107,4.230000,4,1971,0.008335,0.002240,0.991665,0.896920
4,1972-01-01,3307.767,1.240000,23.458,3.436667,1,1972,0.015190,-0.006599,1.098582,0.915100
5,1972-04-01,3370.736,1.280000,23.604,3.770000,2,1972,0.006224,0.003201,1.026034,0.884089
6,1972-07-01,3422.682,1.293333,23.830,4.220000,3,1972,0.009575,0.000975,1.000842,0.903201
7,1972-10-01,3503.001,1.356667,24.134,4.863333,4,1972,0.012757,-0.000599,1.036212,0.861376
8,1973-01-01,3566.957,1.306667,24.412,5.700000,1,1973,0.011519,0.002731,0.951626,0.888157
9,1973-04-01,3565.349,1.196667,24.787,6.603333,2,1973,0.015361,0.001147,0.900455,0.992682
10,1973-07-01,3577.898,1.243333,25.270,8.323333,3,1973,0.019486,0.001322,1.019511,0.969348
11,1973-10-01,3567.227,1.176667,25.773,7.500000,4,1973,0.019905,-0.001155,0.926476,1.007902
12,1974-01-01,3535.312,1.130000,26.260,7.616667,1,1974,0.018896,0.000146,0.941444,1.044848
13,1974-04-01,3548.041,1.020000,26.880,8.153333,2,1974,0.023610,-0.003227,0.879045,0.968880
14,1974-07-01,3563.282,0.833333,27.668,8.190000,3,1974,0.029315,-0.008840,0.787678,0.964863
15,1974-10-01,3511.197,0.836667,28.482,7.360000,4,1974,0.029420,-0.011020,0.974580,1.081447
16,1975-01-01,3540.647,0.976667,29.129,5.750000,1,1975,0.022716,-0.008341,1.144615,0.941609
17,1975-04-01,3598.886,1.120000,29.562,5.393333,2,1975,0.014865,-0.001382,1.131893,0.897682
18,1975-07-01,3650.035,1.076667,30.084,6.330000,3,1975,0.017658,-0.001833,0.943652,0.909623
19,1975-10-01,3689.285,1.116667,30.587,5.626667,4,1975,0.016720,-0.002653,1.020432,0.928462
20,1976-01-01,3763.048,1.276667,30.911,4.916667,1,1976,0.010593,0.001699,1.132691,0.879123
21,1976-04-01,3797.670,1.300000,31.222,5.156667,2,1976,0.010061,0.002831,1.008216,0.937066
22,1976-07-01,3837.654,1.336667,31.626,5.150000,3,1976,0.012940,-0.000065,1.015266,0.929702
23,1976-10-01,3887.447,1.363333,32.192,4.673333,4,1976,0.017897,-0.006213,1.002053,0.916312
24,1977-01-01,3933.268,1.353333,32.711,4.630000,1,1977,0.016122,-0.004547,0.976543,0.922786
25,1977-04-01,3954.596,1.360000,33.172,4.840000,2,1977,0.014093,-0.001993,0.990833,0.958393
26,1977-07-01,3991.989,1.366667,33.576,5.496667,3,1977,0.012179,0.001563,0.992723,0.935647
27,1977-10-01,4052.010,1.353333,34.301,6.110000,4,1977,0.021593,-0.006318,0.968651,0.905208
28,1978-01-01,4074.774,1.313333,34.800,6.393333,1,1978,0.014548,0.001436,0.955896,0.957276
29,1978-04-01,4161.887,1.466667,35.465,6.476667,2,1978,0.019109,-0.002918,1.097642,0.871996
...,...,...,...,...,...,...,...,...,...,...,...
164,2012-01-01,10973.303,56.248710,99.320,0.066667,1,2012,0.006251,-0.006084,1.103782,0.943616
165,2012-04-01,10989.585,56.280159,99.713,0.086667,2,2012,0.003957,-0.003740,0.996602,0.981232
166,2012-07-01,11007.517,58.517778,100.225,0.103333,3,2012,0.005135,-0.004876,1.034624,0.980363
167,2012-10-01,11056.852,59.662742,100.737,0.086667,4,2012,0.005109,-0.004892,1.014458,0.963790
168,2013-01-01,11114.186,64.625000,101.139,0.086667,1,2013,0.003991,-0.003774,1.079181,0.959750
169,2013-04-01,11122.185,68.969531,101.431,0.050000,2,2013,0.002887,-0.002762,1.064340,0.985736
170,2013-07-01,11167.422,72.637812,101.918,0.033333,3,2013,0.004801,-0.004718,1.048386,0.966181
171,2013-10-01,11263.648,77.266406,102.517,0.063333,4,2013,0.005877,-0.005719,1.057844,0.940326
172,2014-01-01,11308.019,80.955574,102.937,0.046667,1,2014,0.004097,-0.003980,1.043649,0.966920
173,2014-04-01,11431.831,83.512063,103.512,0.033333,2,2014,0.005586,-0.005503,1.025993,0.927384
174,2014-07-01,11554.841,86.996406,103.957,0.026667,3,2014,0.004299,-0.004232,1.037424,0.928424
175,2014-10-01,11694.969,88.326719,104.123,0.023333,4,2014,0.001597,-0.001538,1.013695,0.920926
176,2015-01-01,11792.119,91.507541,104.090,0.026667,1,2015,-0.000317,0.000384,1.036329,0.942060
177,2015-04-01,11885.980,93.867937,104.675,0.020000,2,2015,0.005620,-0.005570,1.020174,0.944009
178,2015-07-01,11976.589,90.629688,105.048,0.040000,3,2015,0.003563,-0.003463,0.961939,0.945902
179,2015-10-01,12030.223,91.113438,105.049,0.123333,4,2015,0.000010,0.000299,1.005328,0.963811
180,2016-01-01,12124.214,86.048525,104.941,0.286667,1,2016,-0.001028,0.001745,0.945439,0.944834
181,2016-04-01,12211.285,92.536094,105.657,0.256667,2,2016,0.006823,-0.006181,1.068571,0.948393
182,2016-07-01,12289.063,97.382344,106.043,0.296667,3,2016,0.003653,-0.002912,1.048718,0.952995
183,2016-10-01,12365.312,99.383810,106.551,0.430000,4,2016,0.004791,-0.003716,1.015762,0.953932
184,2017-01-01,12438.898,106.462258,107.058,0.590000,1,2017,0.004758,-0.003283,1.066465,0.955376
185,2017-04-01,12512.899,109.988095,107.411,0.890000,2,2017,0.003297,-0.001072,1.029821,0.955386
186,2017-07-01,12586.281,113.484127,107.973,1.036667,3,2017,0.005232,-0.002641,1.026553,0.955869
187,2017-10-01,12729.713,120.347619,108.713,1.206667,4,2017,0.006854,-0.003837,1.053626,0.924928
188,2018-01-01,12782.902,126.824098,109.355,1.560000,1,2018,0.005905,-0.002005,1.047909,0.965540
189,2018-04-01,12909.192,126.711094,110.281,1.840000,2,2018,0.008468,-0.003868,0.990641,0.933292
190,2018-07-01,13019.802,134.328571,110.767,2.040000,3,2018,0.004407,0.000693,1.055710,0.940596
191,2018-10-01,13066.302,126.443492,111.256,2.316667,4,2018,0.004415,0.001377,0.936885,0.969048
192,2019-01-01,13103.317,128.690492,111.473,2.386667,1,2019,0.001950,0.004016,1.015820,0.973338
193,2019-04-01,13241.083,136.506508,112.164,2.300000,2,2019,0.006199,-0.000449,1.054536,0.929783

In [54]:
dataframe.to_csv('dataset.csv')